version: '3.8'

services:
  epgbuilder:
    image: slapshot18/epgbuilder:latest
    container_name: epgbuilder
    environment:
      - M3U_URL=http://192.168.1.254:36400/a0859edd-0f91-45e8-9cdf-f06ed9126ba2/playlist.m3u
      - CRON_SCHEDULE=0 4 * * *
    volumes:
      - ./output:/output
      - ./config:/config
    restart: unless-stopped