version: '3.8'

services:
  strm_builder:
    image: strm_builder:local
    container_name: strm_builder
    environment:
      - PPV_M3U_URL=http://192.168.1.254:36400/a0bddd39-8259-4cfa-b03c-b1946c56c1c3/playlist.m3u
    volumes:
      - ./output/strm:/output
      - ./config:/config
    ports:
      - "8080:8080"
    restart: no