host: http://localhost:8080
port: 8080
always_accept_pattern_matched_events: true
min_match_percentage: 50
m3u:
  - name: "espn_plus"
    url: "http://192.168.1.254:36400/a0bddd39-8259-4cfa-b03c-b1946c56c1c3/playlist.m3u"
    pattern: \|\s*(?P<event_name>.+?)\s(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b.*?(?P<tz>[A-Z]{2,4})\s*\((?P<date_str>\d{4}-\d{2}-\d{2})\s(?P<start_time>\d{2}:\d{2}:\d{2})
    tz: "America/New_York"
